import { DrugProfile } from "./src/types";

export const DRUG_PROFILES: Record<string, DrugProfile> = {
  metformin: {
    genericName: "Metformin",
    brandNames: ["Glucophage", "Glucophage XR", "Fortamet", "Glumetza"],
    drugClass: "Biguanide Oral Antidiabetic",
    mechanismOfAction: "Decreases hepatic gluconeogenesis by activating AMP-activated protein kinase (AMPK). It also increases insulin sensitivity in peripheral tissues (improving glucose uptake and utilization) and decreases intestinal absorption of glucose.",
    pharmacologicalEffects: "Lowers both basal and postprandial plasma glucose without causing hypoglycemia or weight gain. Often promotes modest weight loss and improves lipid profiles.",
    indications: ["Type 2 Diabetes Mellitus (first-line)", "Polycystic Ovary Syndrome (PCOS, off-label)"],
    dosageAndAdministration: "Standard starting dose: 500 mg orally once or twice daily with meals. Max dose: 2550 mg/day (immediate-release) or 2000 mg/day (extended-release). Administer with meals to decrease gastrointestinal side effects.",
    commonSideEffects: ["Diarrhea", "Nausea and vomiting", "Abdominal bloating/flatulence", "Metallic taste", "Vitamin B12 deficiency (long-term use)"],
    seriousAdverseEffects: ["Lactic Acidosis (rare but fatal, boxed warning)", "Severe hypersensitivity reactions", "Megaloblastic anemia"],
    contraindications: ["Severe renal impairment (eGFR < 30 mL/min/1.73 m²)", "Acute or chronic metabolic acidosis (including diabetic ketoacidosis)"],
    drugDrugInteractions: ["Iodinated contrast media (increases risk of lactic acidosis; withhold metformin before/at the time of procedure)", "Cimetidine or Dolutegravir (increases metformin levels by competing for renal organic cation transporters (OCT2))", "Carbonic anhydrase inhibitors (e.g. topiramate; increases risk of lactic acidosis)"],
    drugFoodInteractions: ["Alcohol (increases the risk of lactic acidosis; avoid excessive intake)", "Food (slows absorption and decreases GI side effects)"],
    monitoringParameters: ["Renal function (serum creatinine, eGFR) at baseline and annually", "Fasting blood glucose and HbA1c every 3-6 months", "Vitamin B12 levels every 2-3 years during long-term therapy"],
    patientCounseling: ["Take with meals to reduce stomach upset.", "Swallow extended-release tablets whole; do not crush, chew, or split.", "Report severe tiredness, muscle pain, fast breathing, or cold feeling immediately (signs of lactic acidosis).", "Avoid excessive alcohol consumption."],
    storageInformation: "Store at 20°C to 25°C (68°F to 77°F); protect from moisture and light.",
    patientFactorDependency: "Contraindicated if eGFR < 30 mL/min. Safe in pregnancy (though insulin is preferred). Geriatric patients have increased risk of lactic acidosis due to age-related renal decline; initiate at lower end of dosing.",
    pharmacyStudentTip: "Metformin is unique among antidiabetics because it does NOT cause hypoglycemia or weight gain, as it is not an insulin secretagogue. Remember the eGFR cutoff of 30 mL/min for exams!"
  },
  lisinopril: {
    genericName: "Lisinopril",
    brandNames: ["Prinivil", "Zestril"],
    drugClass: "Angiotensin-Converting Enzyme (ACE) Inhibitor; Antihypertensive",
    mechanismOfAction: "Competitively inhibits ACE, blocking the conversion of Angiotensin I to Angiotensin II (a potent vasoconstrictor and stimulator of aldosterone). This results in decreased vasopressor activity and decreased aldosterone secretion. Also inhibits the degradation of bradykinin, leading to vasodilation.",
    pharmacologicalEffects: "Reduces systemic vascular resistance, lowers blood pressure, decreases preload and afterload, and retards progressive renal damage in diabetic nephropathy.",
    indications: ["Hypertension", "Heart Failure with reduced ejection fraction (HFrEF, adjunct)", "Acute Myocardial Infarction (within 24 hours of onset to improve survival)"],
    dosageAndAdministration: "Hypertension: Starting 10 mg orally once daily; maintenance 20-40 mg daily. Heart Failure: Starting 2.5-5 mg once daily; titrate to target 20-40 mg daily.",
    commonSideEffects: ["Dry cough", "Dizziness/orthostatic hypotension", "Headache", "Hyperkalemia", "Increased serum creatinine"],
    seriousAdverseEffects: ["Angioedema (life-threatening, boxed warning)", "Acute kidney injury", "Neutropenia/agranulocytosis", "Fetal toxicity (boxed warning)"],
    contraindications: ["History of ACE inhibitor-induced angioedema", "Co-administration with aliskiren in patients with diabetes", "Pregnancy"],
    drugDrugInteractions: ["Potassium-sparing diuretics or potassium supplements (increases risk of hyperkalemia)", "NSAIDs (can decrease antihypertensive efficacy and increase risk of acute renal failure)", "Lithium (ACE inhibitors decrease lithium clearance, increasing toxicity risk)"],
    drugFoodInteractions: ["Avoid excessive potassium-rich foods (e.g., bananas, spinach, salt substitutes containing potassium)"],
    monitoringParameters: ["Serum potassium level", "Serum creatinine/eGFR (assess renal function)", "Blood pressure (especially after first dose and during titration)"],
    patientCounseling: ["Avoid potassium supplements or salt substitutes unless directed.", "Notify provider immediately if swelling of the face, lips, tongue, or throat occurs (signs of angioedema).", "A persistent dry cough may develop; do not use OTC cough remedies.", "Rise slowly from sitting or lying positions to prevent dizziness."],
    storageInformation: "Store at 20°C to 25°C (68°F to 77°F); protect from moisture.",
    patientFactorDependency: "Renal dosage adjustment required for eGFR < 30 mL/min. Contraindicated in pregnancy (fetal toxicity, Category D). African American patients have a higher risk of angioedema and may show a reduced antihypertensive response to monotherapy.",
    pharmacyStudentTip: "The dry cough caused by Lisinopril is due to the accumulation of bradykinin in the respiratory tract. Switching to an Angiotensin Receptor Blocker (ARB) like Losartan avoids this because ARBs do not affect ACE or bradykinin levels."
  },
  losartan: {
    genericName: "Losartan",
    brandNames: ["Cozaar"],
    drugClass: "Angiotensin II Receptor Blocker (ARB); Antihypertensive",
    mechanismOfAction: "Selectively and competitively blocks the binding of Angiotensin II to the AT1 receptor in vascular smooth muscle and the adrenal gland, blocking its vasoconstricting and aldosterone-secreting effects.",
    pharmacologicalEffects: "Lowers systemic vascular resistance and blood pressure. Unlike ACE inhibitors, it does not affect bradykinin, avoiding dry cough.",
    indications: ["Hypertension", "Diabetic Nephropathy in patients with Type 2 Diabetes and Hypertension", "Stroke risk reduction in patients with Hypertension and Left Ventricular Hypertrophy (LVH)"],
    dosageAndAdministration: "Hypertension: Standard starting dose is 50 mg orally once daily; maintenance range is 25-100 mg daily in 1 or 2 divided doses.",
    commonSideEffects: ["Dizziness", "Headache", "Hyperkalemia", "Hypotension", "Fatigue"],
    seriousAdverseEffects: ["Angioedema (rare compared to ACE inhibitors)", "Acute kidney injury", "Fetal toxicity (boxed warning)"],
    contraindications: ["Pregnancy", "Co-administration with aliskiren in patients with diabetes"],
    drugDrugInteractions: ["Potassium supplements/potassium-sparing diuretics (hyperkalemia risk)", "NSAIDs (renal impairment risk and decreased antihypertensive effect)", "Lithium (increased lithium levels and toxicity)"],
    drugFoodInteractions: ["Avoid potassium-containing salt substitutes and excess high-potassium foods."],
    monitoringParameters: ["Serum potassium", "Serum creatinine/eGFR", "Blood pressure"],
    patientCounseling: ["Avoid potassium supplements.", "Do not take if pregnant; stop immediately and contact your doctor if pregnancy is suspected.", "Report any swelling of face, lips, tongue, or breathing difficulties immediately."],
    storageInformation: "Store at 20°C to 25°C (68°F to 77°F); protect from light.",
    patientFactorDependency: "No initial dose adjustment for renal impairment unless volume depleted. Initial dose of 25 mg is recommended in patients with hepatic impairment. Contraindicated in pregnancy.",
    pharmacyStudentTip: "Losartan is an AT1 receptor blocker. It does not inhibit ACE, so bradykinin is metabolized normally, resulting in a negligible rate of dry cough. This makes it a primary alternative for patients who develop Lisinopril cough!"
  },
  atorvastatin: {
    genericName: "Atorvastatin",
    brandNames: ["Lipitor"],
    drugClass: "HMG-CoA Reductase Inhibitor (High-Intensity Statins)",
    mechanismOfAction: "Inhibits 3-hydroxy-3-methylglutaryl-coenzyme A (HMG-CoA) reductase, the rate-limiting enzyme in cholesterol biosynthesis. This upregulates hepatic LDL receptors, increasing LDL clearance from systemic circulation.",
    pharmacologicalEffects: "Significantly lowers LDL-C (by 30% to >50%), reduces Apolipoprotein B and triglycerides, and moderately increases HDL-C. Promotes plaque stabilization and exerts anti-inflammatory (pleiotropic) vascular effects.",
    indications: ["Hypercholesterolemia (primary and familial)", "Primary and Secondary prevention of Cardiovascular Disease (stroke, MI, revascularization)"],
    dosageAndAdministration: "Standard dose: 10-80 mg orally once daily. Can be taken at any time of day, with or without food, due to its long half-life (~14 hours).",
    commonSideEffects: ["Myalgia (muscle pain)", "Arthralgia (joint pain)", "Diarrhea/dyspepsia", "Mild elevation of hepatic transaminases", "Nasopharyngitis"],
    seriousAdverseEffects: ["Rhabdomyolysis (severe muscle breakdown with myoglobinuria and acute renal failure)", "Hepatotoxicity (drug-induced liver injury)", "New-onset Type 2 Diabetes (dose-related, benefits outweigh risks)"],
    contraindications: ["Active liver disease", "Pregnancy (traditionally contraindicated, though guidelines have evolved, still avoid in clinical exams)", "Lactation"],
    drugDrugInteractions: ["Strong CYP3A4 inhibitors (e.g., Clarithromycin, Itraconazole, Ritonavir; significantly increase atorvastatin levels, increasing risk of rhabdomyolysis)", "Gemfibrozil (increases statin toxicity, avoid co-administration)", "Cyclosporine (increases atorvastatin levels)"],
    drugFoodInteractions: ["Large amounts of Grapefruit juice (>1.2 L/day) inhibit CYP3A4 and increase atorvastatin exposure and myopathy risk."],
    monitoringParameters: ["Lipid panel (TC, LDL, HDL, TG) at baseline, then 4-12 weeks after initiation/dose changes", "Liver transaminases (ALT/AST) at baseline; repeat clinically if signs of liver injury occur", "Creatine kinase (CK) if muscle pain, weakness, or dark urine develops"],
    patientCounseling: ["Report unexplained muscle pain, tenderness, or weakness immediately, especially if accompanied by fever or dark, tea-colored urine.", "Take at any time of day, but be consistent.", "Avoid drinking large quantities of grapefruit juice."],
    storageInformation: "Store at 20°C to 25°C (68°F to 77°F).",
    patientFactorDependency: "No renal adjustment required. Contraindicated in active hepatic impairment. Categorized as contraindicated in pregnancy (historically Category X; risk of fetal harm).",
    pharmacyStudentTip: "Atorvastatin and Rosuvastatin are the two 'high-intensity' statins at standard therapeutic doses (Atorvastatin 40-80 mg, Rosuvastatin 20-40 mg). Because Atorvastatin has a long half-life, it does not require nighttime dosing, unlike short-acting statins (e.g. Simvastatin)."
  },
  amoxicillin: {
    genericName: "Amoxicillin",
    brandNames: ["Amoxil", "Moxatag"],
    drugClass: "Beta-Lactam Antibiotic; Aminopenicillin",
    mechanismOfAction: "Inhibits bacterial cell wall synthesis by binding to and inactivating penicillin-binding proteins (PBPs), preventing cross-linking of peptidoglycan chains, leading to cell wall lysis and bacterial death.",
    pharmacologicalEffects: "Bactericidal activity against susceptible Gram-positive and select Gram-negative organisms (e.g. H. influenzae, E. coli, Proteus mirabilis).",
    indications: ["Acute Otitis Media", "Streptococcal Pharyngitis/Tonsillitis", "Lower Respiratory Tract Infections (community-acquired pneumonia)", "H. pylori eradication (as part of multi-drug regimen)"],
    dosageAndAdministration: "Standard adult dose: 500-1000 mg orally every 8-12 hours. Pediatric dose based on weight: 20-90 mg/kg/day in divided doses.",
    commonSideEffects: ["Diarrhea", "Nausea and vomiting", "Maculopapular skin rash (non-allergic, common with Epstein-Barr virus co-infection)", "Oral candidiasis (thrush)"],
    seriousAdverseEffects: ["Anaphylaxis (severe IgE-mediated hypersensitivity)", "Clostridioides difficile-associated diarrhea (CDAD)", "Stevens-Johnson Syndrome (SJS)"],
    contraindications: ["Serious hypersensitivity (e.g., anaphylaxis, SJS) to amoxicillin or other beta-lactams"],
    drugDrugInteractions: ["Probenecid (decreases renal tubular secretion of amoxicillin, increasing its serum levels)", "Oral contraceptives (theoretical reduction in efficacy; use back-up barrier method)", "Allopurinol (increases risk of developing amoxicillin-induced skin rash)"],
    drugFoodInteractions: ["May be taken with or without food. Food may improve gastrointestinal tolerance."],
    monitoringParameters: ["Signs of anaphylaxis/allergic reactions (especially after initial doses)", "Renal function in severe impairment", "Resolution of infectious symptoms (fever, WBC count)"],
    patientCounseling: ["Complete the entire course of therapy even if feeling better.", "Shake liquid suspension well before use and store in the refrigerator (discard after 14 days).", "Report severe watery diarrhea or stomach cramps immediately.", "Can take with food to minimize stomach upset."],
    storageInformation: "Reconstituted oral suspension must be refrigerated and discarded after 14 days.",
    patientFactorDependency: "Requires dosage interval adjustment in severe renal impairment (CrCl < 30 mL/min). Safe in pregnancy and lactation (Category B, drug of choice for many maternal infections).",
    pharmacyStudentTip: "Amoxicillin is susceptible to degradation by beta-lactamase producing bacteria. When paired with Clavulanate (a beta-lactamase inhibitor), it becomes Augmentin, expanding coverage to resistant strains like H. influenzae and M. catarrhalis."
  },
  albuterol: {
    genericName: "Albuterol (Salbutamol)",
    brandNames: ["ProAir HFA", "Ventolin HFA", "Proventil HFA", "Accuneb"],
    drugClass: "Short-Acting Beta-2 Adrenergic Agonist (SABA); Bronchodilator",
    mechanismOfAction: "Selectively stimulates beta-2 adrenergic receptors in bronchial smooth muscle, activating adenylyl cyclase and increasing intracellular cyclic AMP (cAMP). This activates protein kinase A, decreasing intracellular calcium and causing smooth muscle relaxation and bronchodilation.",
    pharmacologicalEffects: "Rapid relaxation of bronchial smooth muscle, relieving acute bronchospasm and reducing airway resistance within 5-15 minutes.",
    indications: ["Treatment or prevention of bronchospasm in asthma and COPD", "Prevention of exercise-induced bronchospasm (EIB)"],
    dosageAndAdministration: "Acute bronchospasm: 2 inhalations orally via MDI every 4-6 hours as needed. Exercise-induced: 2 inhalations 15-30 minutes before exercise.",
    commonSideEffects: ["Tremor (skeletal muscle activation)", "Tachycardia/palpitations", "Nervousness/hyperactivity", "Hypokalemia (potassium shifts into cells at high doses)", "Headache"],
    seriousAdverseEffects: ["Paradoxical bronchospasm (life-threatening airway constriction)", "Severe cardiac arrhythmias", "Hypokalemia-induced QTc prolongation"],
    contraindications: ["Hypersensitivity to albuterol or milk proteins (for dry powder inhalers)"],
    drugDrugInteractions: ["Beta-blockers (non-selective, e.g. Propranolol; antagonize bronchodilatory effects and may induce severe bronchospasm)", "Diuretics (loop/thiazide; may potentiate hypokalemia)", "MAO inhibitors or TCAs (increase risk of cardiovascular toxicity)"],
    drugFoodInteractions: ["Excessive caffeine intake may increase nervousness, palpitations, and tremors."],
    monitoringParameters: ["Asthma control (frequency of SABA rescue inhaler use; >2 days/week indicates poor control)", "Heart rate, blood pressure, and lung function (FEV1, peak flow)", "Serum potassium levels (with high systemic doses)"],
    patientCounseling: ["Keep this 'rescue' inhaler with you at all times.", "Shake the inhaler well before each use.", "If using for exercise, inhale 15-30 minutes before activity.", "Exhale fully, place mouthpiece in mouth, press canister while taking a slow, deep breath, and hold your breath for 10 seconds."],
    storageInformation: "Store at room temperature. Do not puncture or incinerate canister.",
    patientFactorDependency: "Safe in pediatric and geriatric populations at appropriate doses. Use with caution in patients with underlying cardiovascular disease (coronary artery disease, arrhythmias). Safe in pregnancy (inhaled form is preferred rescue agent).",
    pharmacyStudentTip: "Frequent use of albuterol (>2 days per week for rescue, excluding exercise prevention) indicates poorly controlled asthma and suggests the need to initiate or step up controller therapy, such as an inhaled corticosteroid (ICS)."
  },
  gabapentin: {
    genericName: "Gabapentin",
    brandNames: ["Neurontin", "Gralise", "Horizant"],
    drugClass: "GABA Analog; Calcium Channel Blocker (Gabapentinoid)",
    mechanismOfAction: "Binds with high affinity to the alpha-2-delta-1 auxiliary subunit of voltage-gated calcium channels in central nervous system neurons. This decreases calcium influx, reducing the presynaptic release of excitatory neurotransmitters (e.g., glutamate, substance P).",
    pharmacologicalEffects: "Exerts anticonvulsant and analgesic properties. Despite being a structural analog of GABA, it does not bind to GABA-A or GABA-B receptors and does not affect GABA uptake or degradation.",
    indications: ["Postherpetic Neuralgia (PHN)", "Adjunctive therapy in partial onset seizures", "Restless Legs Syndrome (RLS, Horizant)", "Neuropathic pain/fibromyalgia (off-label)"],
    dosageAndAdministration: "Standard seizure/pain dosing: Initiated at 300 mg orally on Day 1, titrated up to 900-3600 mg/day in 3 divided doses. Doses >1800 mg/day show saturated absorption due to active transport transporter limits.",
    commonSideEffects: ["Somnolence (drowsiness)", "Dizziness/ataxia", "Peripheral edema (swelling of hands/feet)", "Fatigue", "Nystagmus"],
    seriousAdverseEffects: ["Suicidal ideation/behavioral changes", "Respiratory depression (especially when combined with opioids or in COPD)", "Severe withdrawal symptoms if abruptly discontinued"],
    contraindications: ["Hypersensitivity to gabapentin"],
    drugDrugInteractions: ["Opioids (e.g. morphine; synergistic CNS and respiratory depression, increase gabapentin levels)", "Antacids (aluminum/magnesium hydroxide; decrease gabapentin bioavailability by ~20%; separate by at least 2 hours)"],
    drugFoodInteractions: ["Food has no effect on immediate-release formulations but may increase absorption of extended-release forms (Gralise)."],
    monitoringParameters: ["Renal function (eGFR/creatinine clearance; drug is 100% renally cleared)", "Mood changes, depression, or suicidal thoughts", "Frequency of seizures or pain intensity"],
    patientCounseling: ["May cause significant drowsiness and dizziness; avoid driving or operating machinery until effects are known.", "Do not stop taking this medication suddenly, as withdrawal can trigger seizures.", "Separate doses of antacids from gabapentin by at least 2 hours."],
    storageInformation: "Store at 20°C to 25°C (68°F to 77°F).",
    patientFactorDependency: "Renal dose adjustments are mandatory for CrCl < 60 mL/min due to 100% renal elimination. Use with caution in elderly patients due to increased fall risk. Classified as Category C in pregnancy.",
    pharmacyStudentTip: "Gabapentin absorption is non-linear. As the oral dose increases, bioavailability decreases because the L-amino acid transporter system in the gut becomes saturated. Splitting a high daily dose into three divided doses improves overall absorption!"
  },
  amlodipine: {
    genericName: "Amlodipine",
    brandNames: ["Norvasc"],
    drugClass: "Dihydropyridine Calcium Channel Blocker (CCB); Antihypertensive",
    mechanismOfAction: "Inhibits the transmembrane influx of calcium ions into vascular smooth muscle and cardiac muscle cells by blocking L-type (long-lasting) voltage-gated calcium channels. This causes arterial vasodilation, reducing peripheral vascular resistance.",
    pharmacologicalEffects: "Lowers blood pressure, decreases myocardial oxygen demand by reducing afterload, and improves oxygen delivery to the myocardium by dilating coronary arteries.",
    indications: ["Hypertension", "Chronic Stable Angina", "Vasospastic (Prinzmetal's) Angina"],
    dosageAndAdministration: "Starting dose: 5 mg orally once daily. Maintenance: 5-10 mg orally once daily. Maximum dose: 10 mg/day.",
    commonSideEffects: ["Peripheral edema (caused by precapillary vasodilation and fluid shifts)", "Flushing", "Dizziness/lightheadedness", "Palpitations (reflex tachycardia, rare)", "Headache"],
    seriousAdverseEffects: ["Worsening of angina or myocardial infarction (on drug initiation or dose escalation)", "Severe hypotension", "Cardiogenic shock"],
    contraindications: ["Severe hypotension", "Hypersensitivity to dihydropyridine CCBs"],
    drugDrugInteractions: ["Simvastatin (amlodipine increases simvastatin levels; limit simvastatin dose to maximum 20 mg/day)", "CYP3A4 inhibitors (e.g. ketoconazole, clarithromycin; increase amlodipine levels)", "CYP3A4 inducers (e.g. rifampin; decrease amlodipine levels)"],
    drugFoodInteractions: ["Grapefruit juice may increase blood levels of amlodipine but has minimal clinical significance compared to other CCBs."],
    monitoringParameters: ["Blood pressure and heart rate", "Signs of peripheral edema (ankles/feet swelling)", "Frequency of angina episodes"],
    patientCounseling: ["Report any swelling of ankles or feet. It is a common side effect of the drug's relaxing effect on blood vessels, not heart failure.", "Rise slowly to avoid lightheadedness.", "Do not stop taking without consulting your doctor."],
    storageInformation: "Store at room temperature in a tight, light-resistant container.",
    patientFactorDependency: "No dose adjustment needed for renal impairment. Half-life is prolonged in hepatic impairment; start at 2.5 mg daily. Geriatric patients are sensitive; start at 2.5 mg daily.",
    pharmacyStudentTip: "Remember that amlodipine is a DIHYDROPYRIDINE CCB, which works selectively on VASCULAR smooth muscle, causing vasodilation. In contrast, NON-dihydropyridines like Diltiazem and Verapamil act on the HEART (cardiac tissue), reducing heart rate and contractility."
  },
  omeprazole: {
    genericName: "Omeprazole",
    brandNames: ["Prilosec", "Prilosec OTC"],
    drugClass: "Proton Pump Inhibitor (PPI); Antisecretory",
    mechanismOfAction: "Irreversibly binds to and inhibits the hydrogen-potassium ATPase enzyme system (the H+/K+ ATPase, or proton pump) on the secretory surface of gastric parietal cells, blocking the final common pathway of acid secretion.",
    pharmacologicalEffects: "Suppresses gastric acid secretion, elevating gastric pH and facilitating mucosal healing in peptic ulcers and reflux esophagitis.",
    indications: ["Gastroesophageal Reflux Disease (GERD)", "Erosive Esophagitis", "Duodenal and Gastric Ulcers", "Pathological hypersecretory conditions (e.g., Zollinger-Ellison syndrome)", "H. pylori eradication (adjunct)"],
    dosageAndAdministration: "Standard adult dose: 20-40 mg orally once daily, administered 30-60 minutes before the first meal of the day (usually breakfast).",
    commonSideEffects: ["Headache", "Abdominal pain/nausea", "Diarrhea", "Flatulence"],
    seriousAdverseEffects: ["Clostridioides difficile-associated diarrhea (CDAD)", "Hypomagnesemia (long-term use)", "Bone fractures (osteoporosis-related, long-term use)", "Chronic Kidney Disease/interstitial nephritis", "Vitamin B12 deficiency"],
    contraindications: ["Hypersensitivity to PPIs", "Co-administration with rilpivirine-containing products"],
    drugDrugInteractions: ["Clopidogrel (omeprazole inhibits CYP2C19, preventing the bioactivation of clopidogrel and reducing its antiplatelet efficacy)", "Ketoconazole, Itraconazole, iron (decreased absorption due to increased gastric pH)", "Methotrexate (PPIs may increase methotrexate levels, leading to toxicity)"],
    drugFoodInteractions: ["Must be taken on an empty stomach, 30-60 minutes before a meal, to maximize efficacy, as the proton pumps are most active during meals."],
    monitoringParameters: ["Serum magnesium levels during long-term therapy (>1 year)", "Bone mineral density in patients at risk for osteoporosis", "Complete blood count and Vitamin B12 in long-term therapy"],
    patientCounseling: ["Take 30 to 60 minutes BEFORE breakfast.", "Swallow capsules whole; do not crush or chew.", "Do not take this medication indefinitely without consulting a provider; long-term use has risks such as low magnesium and bone fractures."],
    storageInformation: "Store at 20°C to 25°C (68°F to 77°F); protect from moisture.",
    patientFactorDependency: "No dose adjustment required for renal impairment. Hepatic clearance is reduced in liver disease; consider dose reduction, especially for maintenance. Safe in pregnancy (Category C, but widely used).",
    pharmacyStudentTip: "Omeprazole is a prodrug that is stable at neutral pH but rapidly activated in the acidic canaliculi of parietal cells. It is enteric-coated to prevent premature activation by stomach acid before absorption in the duodenum!"
  },
  levothyroxine: {
    genericName: "Levothyroxine (T4)",
    brandNames: ["Synthroid", "Levoxyl", "Unithroid", "Tirosint"],
    drugClass: "Thyroid Hormone Replacement",
    mechanismOfAction: "A synthetic form of thyroxine (T4) hormone. It is converted in peripheral tissues to the active thyroid hormone, triiodothyronine (T3). T3 binds to thyroid hormone receptors in cell nuclei, promoting gene transcription, protein synthesis, and increasing metabolic rate.",
    pharmacologicalEffects: "Restores normal thyroid hormone levels, normalizing metabolic rate, body temperature, cardiovascular activity, and growth.",
    indications: ["Hypothyroidism (primary, secondary, or tertiary)", "Pituitary TSH suppression (for thyroid cancer treatment)"],
    dosageAndAdministration: "Standard adult replacement dose: ~1.6 mcg/kg/day orally. Start at 12.5-25 mcg/day in elderly or patients with coronary artery disease to avoid cardiac stress. Take in the morning on an empty stomach, 30-60 minutes before breakfast.",
    commonSideEffects: ["Usually none if dose is correct. Signs of therapeutic overdose (hyperthyroidism):", "Tachycardia/palpitations", "Heat intolerance", "Weight loss", "Insomnia", "Anxiety/tremor"],
    seriousAdverseEffects: ["Myocardial infarction or angina (in patients with ischemic heart disease)", "Cardiac arrhythmias (Atrial Fibrillation)", "Accelerated bone loss/osteoporosis (with chronic over-replacement)"],
    contraindications: ["Uncorrected adrenal insufficiency (initiating thyroid hormone can precipitate acute adrenal crisis)", "Acute myocardial infarction (unless caused by hypothyroidism)", "Untreated thyrotoxicosis"],
    drugDrugInteractions: ["Calcium carbonate, Ferrous sulfate, Antacids, Cholestyramine (significantly decrease levothyroxine absorption; separate doses by at least 4 hours)", "Warfarin (thyroid hormone enhances warfarin's anticoagulant effect by increasing clotting factor degradation)", "Insulin/oral antidiabetics (thyroid hormone may increase antidiabetic requirements)"],
    drugFoodInteractions: ["Take on an empty stomach. Soy formula, walnuts, dietary fiber, and espresso coffee can decrease absorption. Separate by 4 hours."],
    monitoringParameters: ["Thyroid Stimulating Hormone (TSH) level: the primary monitoring parameter (target range 0.4-4.0 mIU/L). Check 6-8 weeks after initiation or dose adjustments.", "Free T4 levels", "Heart rate and cardiac symptoms (especially in the elderly)"],
    patientCounseling: ["Take FIRST thing in the morning with a full glass of water, on an empty stomach, at least 30 to 60 minutes before breakfast, coffee, or other medications.", "Do not take calcium, iron, or antacids within 4 hours of this medication.", "This is long-term therapy; do not stop or switch brands without consulting your doctor, as small differences in brands can affect TSH."],
    storageInformation: "Store at room temperature; protect from light and moisture.",
    patientFactorDependency: "TSH targets and doses change in pregnancy (dose requirements typically increase by 30-50%). In elderly patients or those with ischemic heart disease, follow the clinical maxim: 'Start low and go slow' (12.5-25 mcg/day) to prevent cardiac events.",
    pharmacyStudentTip: "Synthroid has a very narrow therapeutic index. In hypothyroidism, monitoring TSH is key: if TSH is high, the levothyroxine dose is too low (insufficient thyroid hormone to feed back and suppress TSH); if TSH is low, the dose is too high."
  },
  warfarin: {
    genericName: "Warfarin",
    brandNames: ["Coumadin", "Jantoven"],
    drugClass: "Vitamin K Antagonist Anticoagulant",
    mechanismOfAction: "Competitively inhibits Vitamin K Epoxide Reductase Complex 1 (VKORC1), blocking the regeneration of active Vitamin K. This depletes active Vitamin K, preventing the gamma-carboxylation and activation of Vitamin K-dependent clotting factors II, VII, IX, and X, as well as endogenous anticoagulant proteins C and S.",
    pharmacologicalEffects: "Reduces the formation of fibrin and inhibits thrombus propagation. Prolongs the prothrombin time (PT) and elevates the International Normalized Ratio (INR).",
    indications: ["Prophylaxis and treatment of venous thromboembolism (DVT and PE)", "Thromboembolic prophylaxis in Atrial Fibrillation", "Prophylaxis of systemic embolism in patients with prosthetic heart valves"],
    dosageAndAdministration: "Initial dose is usually 2-5 mg orally once daily. Maintenance dose is highly individualized, guided by INR monitoring. Administer at the same time every day.",
    commonSideEffects: ["Bleeding (epistaxis, bruising, hematuria, GI bleeding)", "Alopecia (hair loss)"],
    seriousAdverseEffects: ["Major or fatal hemorrhage (boxed warning)", "Warfarin-induced skin necrosis (caused by rapid depletion of Protein C, resulting in hypercoagulability on initiation; bridge with heparin)", "Purple toe syndrome (cholesterol microembolization)"],
    contraindications: ["Pregnancy (causes fetal warfarin syndrome; boxed warning, except in mechanical heart valves)", "Severe hemorrhagic tendencies", "Uncontrolled severe hypertension", "Recent surgery of central nervous system or eye"],
    drugDrugInteractions: ["Strong CYP2C9 inhibitors (e.g., Amiodarone, Sulfamethoxazole/Trimethoprim, Fluconazole; significantly increase warfarin levels and INR, requiring preemptive dose reductions)", "Strong CYP2C9 inducers (e.g., Rifampin, Carbamazepine; decrease levels and INR)", "NSAIDs or Aspirin (increase bleeding risk without necessarily elevating INR)"],
    drugFoodInteractions: ["Foods high in Vitamin K (e.g., kale, spinach, broccoli, green tea) antagonize warfarin's effect, lowering INR. Patients must maintain a CONSISTENT intake of Vitamin K-rich foods.", "Cranberry juice and alcohol can increase INR."],
    monitoringParameters: ["International Normalized Ratio (INR): target range is 2.0-3.0 for most indications (e.g., AF, DVT) and 2.5-3.5 for mechanical mitral valves.", "Hemoglobin/Hematocrit (to monitor for occult bleeding)", "Signs and symptoms of bleeding"],
    patientCounseling: ["Take exactly as prescribed at the same time each day.", "Regular blood tests (INR) are mandatory.", "Maintain a consistent diet of green leafy vegetables (do not suddenly increase or decrease intake of Vitamin K).", "Report any unusual bleeding, dark or tarry stools, or severe bruising immediately.", "Avoid pregnancy while taking this medication."],
    storageInformation: "Store at 20°C to 25°C (68°F to 77°F); protect from light.",
    patientFactorDependency: "Highly sensitive in patients with hepatic impairment (decreased synthesis of clotting factors) and elderly. Contraindicated in pregnancy (Category X / fetal bleeding). Polymorphisms in CYP2C9 and VKORC1 alter dose requirements (pharmacogenomics).",
    pharmacyStudentTip: "On initiation, warfarin transiently causes a HYPERcoagulable state because Protein C (an anticoagulant) has a much shorter half-life (~8 hours) than Factor II (prothrombin, half-life ~60 hours). This is why heparin bridging is required in patients with active clots!"
  },
  apixaban: {
    genericName: "Apixaban",
    brandNames: ["Eliquis"],
    drugClass: "Direct Factor Xa Inhibitor (DOAC - Direct Oral Anticoagulant)",
    mechanismOfAction: "Selectively, reversibly, and directly binds to and inhibits active Factor Xa (both free and clot-bound) as well as prothrombinase activity, blocking the conversion of prothrombin to thrombin.",
    pharmacologicalEffects: "Prevents thrombin generation and thrombus formation. Inhibits coagulation with a rapid onset (peaks in 3-4 hours) and predictable pharmacokinetics.",
    indications: ["Reduction of stroke and systemic embolism in non-valvular Atrial Fibrillation", "Prophylaxis and treatment of Deep Vein Thrombosis (DVT) and Pulmonary Embolism (PE)"],
    dosageAndAdministration: "Non-valvular Atrial Fibrillation: Standard dose is 5 mg orally twice daily. Reduce to 2.5 mg twice daily if the patient meets at least TWO of the following criteria: Age >= 80 years, Body weight <= 60 kg, or Serum creatinine >= 1.5 mg/dL.",
    commonSideEffects: ["Bleeding (epistaxis, hematuria, gingival bleeding)", "Anemia", "Nausea"],
    seriousAdverseEffects: ["Major hemorrhage (intracranial, gastrointestinal)", "Spinal/epidural hematoma (boxed warning in patients undergoing neuraxial anesthesia)", "Increased risk of stroke/thrombotic events if prematurely discontinued without alternative anticoagulation (boxed warning)"],
    contraindications: ["Active pathological bleeding", "Severe hypersensitivity to apixaban", "Prosthetic heart valves (clinical trials showed worse outcomes than warfarin)"],
    drugDrugInteractions: ["Dual strong CYP3A4 and P-gp inhibitors (e.g., Ketoconazole, Itraconazole, Ritonavir; increase apixaban levels and bleeding risk; adjust dose or avoid)", "Dual strong CYP3A4 and P-gp inducers (e.g., Rifampin, Carbamazepine, St. John's Wort; decrease levels and efficacy; avoid)"],
    drugFoodInteractions: ["No significant food interactions. Can be taken with or without food."],
    monitoringParameters: ["No routine coagulation monitoring (e.g., INR) is required.", "Renal function (eGFR/creatinine) and hepatic function at baseline and periodically.", "Hemoglobin and hematocrit levels."],
    patientCounseling: ["Take twice daily, with or without food.", "Do not stop taking this medication without consulting your doctor, as stopping increases your risk of stroke.", "Report signs of bleeding immediately (e.g., coughing up blood, dark/tarry stools, nosebleeds that do not stop within 10 minutes)."],
    storageInformation: "Store at room temperature.",
    patientFactorDependency: "Renal dosage adjustment based on criteria (age, weight, creatinine). Avoid use in patients with severe hepatic impairment (Child-Pugh C). Safe use in pregnancy is not established; avoid.",
    pharmacyStudentTip: "Apixaban does not require routine blood monitoring like Warfarin, making it highly preferred. Its reversal agent is Andexanet Alfa (Andexxa), which acts as a decoy Factor Xa molecule!"
  },
  furosemide: {
    genericName: "Furosemide",
    brandNames: ["Lasix"],
    drugClass: "Loop Diuretic",
    mechanismOfAction: "Inhibits the luminal sodium-potassium-chloride cotransporter (NKCC2) in the thick ascending limb of the loop of Henle, blocking the reabsorption of sodium, potassium, chloride, and water.",
    pharmacologicalEffects: "Promotes marked diuresis and natriuresis. Increases the excretion of water, sodium, potassium, chloride, calcium, and magnesium. Reduces intravascular volume, lowering blood pressure and systemic edema.",
    indications: ["Edema associated with Congestive Heart Failure, Hepatic Cirrhosis, or Renal Disease", "Hypertension (adjunct, especially in patients with severe renal impairment)"],
    dosageAndAdministration: "Edema: Starting 20-80 mg orally once daily. Can be titrated up to 600 mg/day in severe refractory cases. Often administered in the morning to prevent nocturia.",
    commonSideEffects: ["Hypokalemia (low potassium)", "Hyponatremia (low sodium)", "Hypomagnesemia", "Dehydration/hypotension", "Hyperuricemia (can precipitate gout)"],
    seriousAdverseEffects: ["Ototoxicity (transient or permanent hearing loss/tinnitus, especially at high IV doses)", "Acute kidney injury/prerenal azotemia", "Severe electrolyte depletion", "Stevens-Johnson Syndrome (sulfa allergy crossover)"],
    contraindications: ["Anuria (inability to produce urine)", "Hepatic coma/severe electrolyte depletion"],
    drugDrugInteractions: ["Aminoglycosides (e.g. Gentamicin; additive ototoxicity)", "NSAIDs (blunt furosemide's diuretic effect and increase risk of renal impairment)", "Digoxin (furosemide-induced hypokalemia significantly increases the risk of digoxin toxicity and cardiac arrhythmias)"],
    drugFoodInteractions: ["Take on an empty stomach to improve absorption, as food can reduce its bioavailability by 30-50%."],
    monitoringParameters: ["Serum electrolytes (potassium, sodium, magnesium, calcium)", "Renal function (BUN, serum creatinine)", "Blood pressure and volume status (daily weights, fluid intake/output)"],
    patientCounseling: ["Take in the morning to avoid waking up at night to urinate. If taken twice daily, take the second dose no later than 4:00 PM.", "Stand up slowly to avoid dizziness.", "Monitor your weight daily and report a sudden gain or loss of more than 3 lbs in a day.", "Consume potassium-rich foods if advised."],
    storageInformation: "Store at room temperature; protect from light.",
    patientFactorDependency: "Requires higher doses in severe renal impairment to reach active tubular site. Use with caution in the elderly (increased risk of dehydration and falls). Contraindicated in pregnancy (secreted in breast milk and reduces placental perfusion).",
    pharmacyStudentTip: "Furosemide is a sulfonamide derivative. Although the cross-reactivity with non-antibiotic sulfonamides is historically debated, watch out for sulfa allergies on exams! Loop diuretics are also unique because they waste calcium ('loops lose calcium'), whereas thiazides conserve it."
  },
  metoprolol: {
    genericName: "Metoprolol (Succinate / Tartrate)",
    brandNames: ["Lopressor (Tartrate)", "Toprol XL (Succinate)"],
    drugClass: "Beta-1 Selective Adrenergic Antagonist (Cardioselective Beta-Blocker)",
    mechanismOfAction: "Competitively blocks beta-1 adrenergic receptors in cardiac muscle, inhibiting the positive chronotropic and inotropic effects of catecholamines (epinephrine and norepinephrine).",
    pharmacologicalEffects: "Decreases heart rate, myocardial contractility, cardiac output, and blood pressure. Decreases myocardial oxygen demand. Sustained-release form (Succinate) improves survival in chronic heart failure.",
    indications: ["Hypertension", "Angina Pectoris", "Heart Failure with reduced ejection fraction (Succinate only)", "Acute Myocardial Infarction (to reduce cardiovascular mortality)"],
    dosageAndAdministration: "Tartrate (Immediate-Release, taken 2-3 times daily with or immediately after meals): 100-450 mg/day. Succinate (Extended-Release, taken once daily): 25-200 mg/day.",
    commonSideEffects: ["Bradycardia (slow heart rate)", "Fatigue/dizziness", "Sexual dysfunction", "Cold extremities (decreased peripheral perfusion)", "Hypotension"],
    seriousAdverseEffects: ["Severe bradycardia/atrioventricular block", "Bronchospasm (in patients with reactive airway disease at high doses)", "Acute heart failure exacerbation (if titrated too rapidly)", "Masking of hypoglycemic symptoms in diabetic patients"],
    contraindications: ["Severe bradycardia (<45 bpm)", "Second- or third-degree heart block", "Decompensated heart failure", "Cardiogenic shock"],
    drugDrugInteractions: ["CCBs (Verapamil / Diltiazem; additive negative inotropic and chronotropic effects, increasing risk of severe bradycardia and AV block)", "Amiodarone (potentiates bradycardia)", "Clonidine (increased risk of rebound hypertension if stopped)"],
    drugFoodInteractions: ["Immediate-release Tartrate absorption is increased with food; take with or immediately after meals. Succinate is unaffected."],
    monitoringParameters: ["Heart rate (hold dose if HR < 55 bpm)", "Blood pressure", "ECG (monitoring for heart blocks)", "Signs of heart failure (edema, dyspnea)"],
    patientCounseling: ["Do not abruptly stop taking this medication. Sudden discontinuation can cause severe rebound hypertension, arrhythmias, or myocardial infarction (boxed warning).", "Toprol XL can be divided but must not be crushed or chewed.", "Rise slowly from lying down."],
    storageInformation: "Store at 20°C to 25°C (68°F to 77°F).",
    patientFactorDependency: "No renal adjustment required. Metoprolol is a CYP2D6 substrate; poor metabolizers have higher drug levels (pharmacogenomics). Use with caution in asthma/COPD due to potential beta-2 receptor crossover.",
    pharmacyStudentTip: "Remember the salt forms: Metoprolol TARTRATE is immediate-release (taken multiple times daily, 'Tart-rate' is 'twice' daily), while Metoprolol SUCCINATE is extended-release (taken once daily, 'Succ-inate' is 'single' daily) and is the only form approved for chronic Heart Failure!"
  },
  ibuprofen: {
    genericName: "Ibuprofen",
    brandNames: ["Advil", "Motrin", "Caldolor"],
    drugClass: "Nonsteroidal Anti-inflammatory Drug (NSAID)",
    mechanismOfAction: "Nonselectively inhibits Cyclooxygenase-1 (COX-1) and Cyclooxygenase-2 (COX-2) enzymes, blocking the conversion of arachidonic acid to prostaglandins, which mediate inflammation, fever, and pain.",
    pharmacologicalEffects: "Anti-inflammatory, analgesic (pain-relieving), and antipyretic (fever-reducing) effects. Reversibly inhibits platelet aggregation.",
    indications: ["Mild to moderate pain", "Rheumatoid Arthritis and Osteoarthritis", "Primary Dysmenorrhea (menstrual cramps)", "Fever reduction"],
    dosageAndAdministration: "OTC analgesic: 200-400 mg orally every 4-6 hours (Max: 1200 mg/day). Prescription anti-inflammatory: 400-800 mg orally every 6-8 hours (Max: 3200 mg/day). Take with food to reduce GI upset.",
    commonSideEffects: ["Dyspepsia (heartburn)", "Abdominal pain/nausea", "Dizziness", "Mild blood pressure elevation"],
    seriousAdverseEffects: ["Gastrointestinal bleeding, ulceration, and perforation (boxed warning)", "Cardiovascular thrombotic events, MI, and stroke (boxed warning)", "Acute kidney injury/renal papillary necrosis", "Drug Reaction with Eosinophilia and Systemic Symptoms (DRESS) syndrome"],
    contraindications: ["Asthma, urticaria, or allergic reactions after taking aspirin or other NSAIDs", "Treatment of perioperative pain in CABG surgery (boxed warning)"],
    drugDrugInteractions: ["Aspirin (ibuprofen competes for platelet COX-1 binding, decreasing aspirin's cardioprotective effect; take ibuprofen 8 hours after or 30 minutes before aspirin)", "Antihypertensives (NSAIDs reduce their effect by inhibiting renal vasodilating prostaglandins)", "Warfarin/DOACs (additive bleeding risk)"],
    drugFoodInteractions: ["Food delays rate of absorption but does not affect extent. Taking with food or milk reduces GI upset."],
    monitoringParameters: ["Renal function (BUN, creatinine) during long-term therapy", "Hemoglobin/hematocrit (for chronic occult GI blood loss)", "Blood pressure (can cause sodium retention and worsen hypertension)"],
    patientCounseling: ["Take with food or milk to minimize stomach irritation.", "Do not take more than the recommended dose, as doing so increases your risk of stomach bleeding and kidney damage.", "Report black, tarry stools, coughing up blood, or sudden swelling in ankles immediately."],
    storageInformation: "Store at room temperature.",
    patientFactorDependency: "Avoid in severe renal impairment. Contraindicated in late pregnancy (>= 30 weeks gestation) as it can cause premature closure of the fetal ductus arteriosus.",
    pharmacyStudentTip: "NSAIDs inhibit renal prostaglandins (specifically PGE2 and PGI2), which normally dilate the afferent arteriole. Inhibiting them constricts the afferent arteriole, reducing glomerular filtration rate (GFR). In contrast, ACE inhibitors dilate the efferent arteriole!"
  },
  sertraline: {
    genericName: "Sertraline",
    brandNames: ["Zoloft"],
    drugClass: "Selective Serotonin Reuptake Inhibitor (SSRI); Antidepressant",
    mechanismOfAction: "Selectively inhibits the presynaptic serotonin reuptake transporter (SERT), prolonging the presence of serotonin (5-HT) in the synaptic cleft and enhancing serotonergic neurotransmission.",
    pharmacologicalEffects: "Ameliorates symptoms of depression, anxiety, and obsessive-compulsive behaviors. Takes 4-6 weeks of continuous administration for full therapeutic onset.",
    indications: ["Major Depressive Disorder (MDD)", "Obsessive-Compulsive Disorder (OCD)", "Panic Disorder", "Post-Traumatic Stress Disorder (PTSD)", "Social Anxiety Disorder", "Premenstrual Dysphoric Disorder (PMDD)"],
    dosageAndAdministration: "Standard starting dose: 25-50 mg orally once daily, in the morning or evening. Can be titrated up to a maximum dose of 200 mg/day.",
    commonSideEffects: ["Nausea and diarrhea (due to abundance of serotonin receptors in the gut)", "Insomnia or somnolence", "Sexual dysfunction (decreased libido, anorgasmia)", "Xerostomia (dry mouth)", "Increased sweating"],
    seriousAdverseEffects: ["Suicidal ideation and behavior in children, adolescents, and young adults (boxed warning)", "Serotonin Syndrome (life-threatening autonomic and neuromuscular hyperactivity)", "QTc prolongation", "SIADH / Hyponatremia", "Discontinuation syndrome (with abrupt withdrawal)"],
    contraindications: ["Co-administration with Monoamine Oxidase Inhibitors (MAOIs; risk of fatal Serotonin Syndrome; requires 14-day washout period)", "Co-administration with Pimozide or Disulfiram (for sertraline liquid concentrate)"],
    drugDrugInteractions: ["MAOIs, Linezolid, Tramadol, triptans, St. John's Wort (potentiate Serotonin Syndrome risk)", "NSAIDs, Aspirin, Warfarin (increase bleeding risk by impairing platelet serotonin uptake without affecting coagulation factors)"],
    drugFoodInteractions: ["Sertraline oral concentrate MUST be diluted with water, ginger ale, lemon/lime soda, lemonade, or orange juice immediately before administration. Food increases sertraline bioavailability by ~25%."],
    monitoringParameters: ["Worsening of depression, suicidal thoughts, or unusual behavior", "Serum sodium levels (especially in the elderly, due to hyponatremia/SIADH risk)", "Signs of Serotonin Syndrome (rigidity, hyperthermia, tachycardia, clonus)"],
    patientCounseling: ["It may take 4 to 6 weeks to see the full therapeutic benefit of this medication.", "Do not stop taking this medication suddenly, as doing so can cause withdrawal symptoms like dizziness, headache, and electric-shock sensations.", "Avoid taking other medications that increase serotonin (such as OTC St. John's Wort) without speaking to your pharmacist."],
    storageInformation: "Store at 20°C to 25°C (68°F to 77°F).",
    patientFactorDependency: "No dosage adjustment required in renal impairment. Hepatic clearance is reduced; use lower doses or reduce frequency in liver impairment. Use with caution in late pregnancy (neonatal adaptation syndrome).",
    pharmacyStudentTip: "Among SSRIs, Sertraline is famous for causing the most gastrointestinal side effects (especially diarrhea, historically nicknamed 'Sertraline-induced squirts' by students). This is because serotonin directly stimulates GI motility via enteric nervous system receptors."
  },
  glipizide: {
    genericName: "Glipizide",
    brandNames: ["Glucotrol", "Glucotrol XL"],
    drugClass: "Second-Generation Sulfonylurea Oral Antidiabetic",
    mechanismOfAction: "Binds to and blocks ATP-sensitive potassium channels (SUR1 subunit) in pancreatic beta-cell membranes. This depolarizes the cell, opening voltage-gated calcium channels, leading to calcium influx and triggering exocytosis of insulin granules.",
    pharmacologicalEffects: "Stimulates pancreatic insulin secretion, lowering blood glucose levels. High risk of inducing hypoglycemia and moderate weight gain.",
    indications: ["Type 2 Diabetes Mellitus (as adjunct to diet and exercise)"],
    dosageAndAdministration: "Immediate-release: 2.5-20 mg/day, administered 30 minutes before a meal (typically breakfast). Doses >15 mg should be divided. Extended-release (XL): 2.5-20 mg once daily with breakfast.",
    commonSideEffects: ["Hypoglycemia", "Weight gain (due to increased insulin anabolic effects)", "Gastrointestinal upset (nausea, dyspepsia)", "Headache"],
    seriousAdverseEffects: ["Severe, prolonged hypoglycemia", "Hemolytic anemia (especially in G6PD deficiency)", "Hepatotoxicity"],
    contraindications: ["Type 1 Diabetes Mellitus (ineffective as beta-cells are destroyed)", "Diabetic ketoacidosis", "Hypersensitivity to sulfonylureas"],
    drugDrugInteractions: ["Beta-blockers (can mask the autonomic warning signs of hypoglycemia, such as tachycardia and tremors)", "Fluconazole (inhibits CYP2C9, significantly increasing glipizide levels and risk of severe hypoglycemia)", "Salicylates, sulfonamides (displace glipizide from protein binding, enhancing hypoglycemic effect)"],
    drugFoodInteractions: ["Immediate-release must be taken 30 minutes before breakfast to ensure optimal insulin release synced with glucose absorption."],
    monitoringParameters: ["Fasting blood glucose and self-monitoring blood glucose charts", "HbA1c every 3-6 months", "Signs of hypoglycemia (sweating, shaking, confusion)"],
    patientCounseling: ["Take 30 minutes before your first meal of the day.", "Always carry a fast-acting source of sugar (like glucose tablets, fruit juice, or hard candies) in case of low blood sugar symptoms.", "Learn to recognize signs of low blood sugar (shakiness, sweating, dizziness, fast heartbeat).", "Do not skip meals after taking this medication."],
    storageInformation: "Store at room temperature; protect from moisture.",
    patientFactorDependency: "Contraindicated in severe renal/hepatic impairment due to increased accumulation and severe hypoglycemia risk. Avoid in the elderly (highly sensitive to hypoglycemia, listed in Beers Criteria).",
    pharmacyStudentTip: "Glipizide is a second-generation sulfonylurea. Unlike first-generation agents (e.g. Chlorpropamide), it has higher potency, shorter half-life, and is much less likely to cause disulfiram-like reactions with alcohol or SIADH."
  }
};
